package cmd

import (
	"fmt"
	"os"
	"os/exec"
	"os/user"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/spf13/cobra"
	"her/config"
)

// tunnelCmd is the parent command for tunnel management.
var tunnelCmd = &cobra.Command{
	Use:   "tunnel",
	Short: "Manage the Cloudflare Tunnel for webhook delivery",
	Long: `Cloudflare Tunnel creates a stable public URL that routes to the local
webhook server, even behind NAT. The tunnel runs as a launchd service
alongside the bot.

Subcommands:
  setup    Generate cloudflared config and install as a launchd service`,
}

// tunnelSetupCmd generates cloudflared config and installs the tunnel
// as a launchd service. Requires cloudflared to be installed and the
// tunnel to already exist (created via "cloudflared tunnel create").
var tunnelSetupCmd = &cobra.Command{
	Use:   "setup",
	Short: "Generate cloudflared config and install as a launchd service",
	Long: `Generates ~/.cloudflared/config.yml from config.yaml tunnel settings and
installs a launchd plist so the tunnel starts automatically on boot.

Prerequisites:
  1. brew install cloudflare/cloudflare/cloudflared
  2. cloudflared tunnel login
  3. cloudflared tunnel create <name>
  4. cloudflared tunnel route dns <name> <domain>
  5. Fill in config.yaml tunnel section (name, domain, credentials_file)

This command then:
  1. Validates cloudflared is installed and tunnel config is present
  2. Generates ~/.cloudflared/config.yml
  3. Generates and installs a launchd plist for the tunnel
  4. Loads the service`,
	RunE: runTunnelSetup,
}

func init() {
	rootCmd.AddCommand(tunnelCmd)
	tunnelCmd.AddCommand(tunnelSetupCmd)
}

// tunnelServiceLabel returns the launchd label for the cloudflared tunnel
// service. Follows the same naming convention as the bot service
// (serviceLabel in setup.go), just with "cloudflared" instead of "her-go".
// e.g., "Mira" → "com.mira.cloudflared"
func tunnelServiceLabel(botName string) string {
	return "com." + strings.ToLower(botName) + ".cloudflared"
}

// tunnelPlistPath returns the full path to the tunnel plist in ~/Library/LaunchAgents.
func tunnelPlistPath(botName string) (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("could not determine home directory: %w", err)
	}
	return filepath.Join(home, "Library", "LaunchAgents", tunnelServiceLabel(botName)+".plist"), nil
}

// cloudflaredConfigData holds the values injected into the cloudflared config template.
type cloudflaredConfigData struct {
	TunnelName      string
	CredentialsFile string
	Domain          string
	WebhookPort     int
}

// cloudflaredConfigTemplate generates ~/.cloudflared/config.yml.
// The ingress rules route the webhook domain to the local bot server
// and return 404 for everything else (required catch-all).
const cloudflaredConfigTemplate = `# Auto-generated by her tunnel setup — edits will be overwritten.
tunnel: {{.TunnelName}}
credentials-file: {{.CredentialsFile}}

ingress:
  - hostname: {{.Domain}}
    service: http://localhost:{{.WebhookPort}}
  - service: http_status:404
`

// tunnelPlistData holds the values injected into the tunnel launchd plist.
type tunnelPlistData struct {
	Label          string
	CloudflaredBin string
	ConfigPath     string
	StdoutPath     string
	StderrPath     string
	UserName       string
}

// tunnelPlistTemplate is the launchd plist for the cloudflared tunnel.
// Same structure as the bot's plist — KeepAlive ensures automatic restart.
const tunnelPlistTemplate = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>{{.Label}}</string>

    <key>ProgramArguments</key>
    <array>
        <string>{{.CloudflaredBin}}</string>
        <string>tunnel</string>
        <string>--config</string>
        <string>{{.ConfigPath}}</string>
        <string>run</string>
    </array>

    <key>KeepAlive</key>
    <true/>

    <key>ThrottleInterval</key>
    <integer>5</integer>

    <key>StandardOutPath</key>
    <string>{{.StdoutPath}}</string>

    <key>StandardErrorPath</key>
    <string>{{.StderrPath}}</string>

    <key>UserName</key>
    <string>{{.UserName}}</string>
</dict>
</plist>
`

func runTunnelSetup(cmd *cobra.Command, args []string) error {
	// Load config.
	cfg, err := config.Load(cfgFile)
	if err != nil {
		return fmt.Errorf("loading config: %w", err)
	}

	// Validate tunnel config is filled in.
	if cfg.Tunnel.Name == "" {
		return fmt.Errorf("config.yaml tunnel.name is empty — run `cloudflared tunnel create <name>` first, then fill in the tunnel section")
	}
	if cfg.Tunnel.Domain == "" {
		return fmt.Errorf("config.yaml tunnel.domain is empty — run `cloudflared tunnel route dns %s <domain>` first", cfg.Tunnel.Name)
	}
	if cfg.Tunnel.CredentialsFile == "" {
		return fmt.Errorf("config.yaml tunnel.credentials_file is empty — this is the JSON file created by `cloudflared tunnel create` (usually ~/.cloudflared/<tunnel-id>.json)")
	}

	// Check cloudflared is installed.
	cloudflaredBin, err := exec.LookPath("cloudflared")
	if err != nil {
		return fmt.Errorf("cloudflared not found — install with: brew install cloudflare/cloudflare/cloudflared")
	}
	log.Info("found cloudflared", "path", cloudflaredBin)

	// Verify credentials file exists.
	if _, err := os.Stat(cfg.Tunnel.CredentialsFile); err != nil {
		return fmt.Errorf("credentials file not found at %s — check tunnel.credentials_file in config.yaml", cfg.Tunnel.CredentialsFile)
	}

	// Determine webhook port (same default as bot/telegram.go).
	webhookPort := cfg.Telegram.WebhookPort
	if webhookPort == 0 {
		webhookPort = 8443
	}

	currentUser, err := user.Current()
	if err != nil {
		return fmt.Errorf("could not determine current user: %w", err)
	}

	home, err := os.UserHomeDir()
	if err != nil {
		return fmt.Errorf("could not determine home directory: %w", err)
	}

	workDir, err := os.Getwd()
	if err != nil {
		return fmt.Errorf("could not determine working directory: %w", err)
	}

	// Step 1: Generate ~/.cloudflared/config.yml.
	log.Info("[1/3] generating cloudflared config")
	cloudflaredDir := filepath.Join(home, ".cloudflared")
	if err := os.MkdirAll(cloudflaredDir, 0o700); err != nil {
		return fmt.Errorf("creating ~/.cloudflared: %w", err)
	}

	cfgData := cloudflaredConfigData{
		TunnelName:      cfg.Tunnel.Name,
		CredentialsFile: cfg.Tunnel.CredentialsFile,
		Domain:          cfg.Tunnel.Domain,
		WebhookPort:     webhookPort,
	}

	configPath := filepath.Join(cloudflaredDir, "config.yml")
	cfgTmpl, err := template.New("cloudflared").Parse(cloudflaredConfigTemplate)
	if err != nil {
		return fmt.Errorf("parsing cloudflared config template: %w", err)
	}

	cfgFile, err := os.Create(configPath)
	if err != nil {
		return fmt.Errorf("creating %s: %w", configPath, err)
	}
	if err := cfgTmpl.Execute(cfgFile, cfgData); err != nil {
		cfgFile.Close()
		return fmt.Errorf("writing cloudflared config: %w", err)
	}
	cfgFile.Close()
	log.Info("wrote cloudflared config", "path", configPath)

	// Step 2: Generate and install the launchd plist.
	log.Info("[2/3] generating tunnel launchd plist")
	logsDir := filepath.Join(workDir, "logs")
	if err := os.MkdirAll(logsDir, 0o755); err != nil {
		return fmt.Errorf("creating logs directory: %w", err)
	}

	plistData := tunnelPlistData{
		Label:          tunnelServiceLabel(cfg.Identity.Her),
		CloudflaredBin: cloudflaredBin,
		ConfigPath:     configPath,
		StdoutPath:     filepath.Join(logsDir, "tunnel-stdout.log"),
		StderrPath:     filepath.Join(logsDir, "tunnel-stderr.log"),
		UserName:       currentUser.Username,
	}

	plistTmpl, err := template.New("plist").Parse(tunnelPlistTemplate)
	if err != nil {
		return fmt.Errorf("parsing tunnel plist template: %w", err)
	}

	dest, err := tunnelPlistPath(cfg.Identity.Her)
	if err != nil {
		return err
	}

	plistFile, err := os.Create(dest)
	if err != nil {
		return fmt.Errorf("creating %s: %w", dest, err)
	}
	if err := plistTmpl.Execute(plistFile, plistData); err != nil {
		plistFile.Close()
		return fmt.Errorf("writing tunnel plist: %w", err)
	}
	plistFile.Close()
	log.Info("wrote tunnel plist", "path", dest)

	// Step 3: Load the service.
	log.Info("[3/3] loading tunnel service")
	loadCmd := exec.Command("launchctl", "load", dest)
	loadCmd.Stdout = os.Stdout
	loadCmd.Stderr = os.Stderr
	if err := loadCmd.Run(); err != nil {
		log.Warn("launchctl load failed — the service may already be loaded. Try: launchctl unload "+dest, "err", err)
	} else {
		log.Info("tunnel service loaded")
	}

	log.Info("tunnel setup complete",
		"config", configPath,
		"plist", dest,
		"domain", cfg.Tunnel.Domain,
		"port", webhookPort,
	)
	log.Info("verify with", "cmd", "curl -I https://"+cfg.Tunnel.Domain)

	return nil
}
