package testutil

import (
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"testing"

	"her/embed"
)

// StubEmbedClient creates an embed.Client backed by a local httptest server.
// Instead of calling a real embedding model, it returns deterministic
// vectors based on a hash of the input text — same algorithm as
// DeterministicEmbedding in db.go.
//
// This means facts seeded with SeedFact (which uses DeterministicEmbedding
// directly) produce the same vectors as facts embedded through this client.
// That's important: it means KNN search actually works in tests — query
// vectors and stored vectors are generated by the same function.
//
// The server is automatically shut down when the test finishes.
//
// Usage:
//
//	embedClient := testutil.StubEmbedClient(t)
//	vec, err := embedClient.Embed("hello world")
//	// vec is a deterministic 4-dimensional vector
func StubEmbedClient(t *testing.T) *embed.Client {
	t.Helper()

	// httptest.NewServer spins up a real HTTP server on localhost with a
	// random port. It's Go's built-in alternative to mocking HTTP calls —
	// the client makes real HTTP requests, they just hit a local handler
	// instead of the internet.
	//
	// This is better than mocking because it exercises the full HTTP path:
	// JSON marshaling, headers, status codes, response parsing. If the
	// embed client has a bug in how it builds requests, this catches it.
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		// Parse the request to get the input text.
		var req struct {
			Model string `json:"model"`
			Input string `json:"input"`
		}
		if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
			http.Error(w, "bad request", http.StatusBadRequest)
			return
		}

		// Generate a deterministic embedding from the input text.
		// This uses the same hash function as SeedFact, so vectors
		// are comparable across the two code paths.
		vec := DeterministicEmbedding(req.Input)

		// Convert to float64 for the JSON response — the real API
		// returns float64, and embed.Client converts back to float32.
		vec64 := make([]float64, len(vec))
		for i, v := range vec {
			vec64[i] = float64(v)
		}

		// Mirror the OpenAI embeddings API response format.
		resp := map[string]interface{}{
			"data": []map[string]interface{}{
				{"embedding": vec64},
			},
		}

		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(resp)
	}))

	t.Cleanup(func() {
		srv.Close()
	})

	// Point the real embed.Client at our stub server.
	// "test-model" is arbitrary — the stub ignores it.
	return embed.NewClient(srv.URL, "test-model", TestEmbedDim)
}
